### ISSUE TITLE
BUG: panic raised on scanning of terraform folder

### ISSUE THREAD

**Issue by williamfalconeruk** [aquasecurity/trivy-action#63]
Hi, 

Hope someone can help:
 We're attempting to run the trivy scanner on one of our terraform folders and are seeing a segmentation fault: 

https://github.com/ministryofjustice/opg-lpa/runs/3382241340?check_suite_focus=true#step:4:20

Note it works on one of our other terraform folders.
not sure if this is something we should be seeing or is a known issue. can someone advise?

**Comment by simar7** [comment]
thanks for the report @williamfalconeruk - I will take a look at it shortly.

**Comment by simar7** [comment]
I took a look at it @williamfalconeruk - I've opened another issue to track it down here https://github.com/aquasecurity/trivy/issues/1193 - this error is actually coming from tfsec (Trivy's downstream dependency for config scanning) rather than Trivy or Trivy Action itself. Looks like something went wrong with one of the rules for AWS scanning and a panic trace was outputted for debug purposes.

Running the Trivy scan locally seems to be fine as you may have seen. You can try it as follows:
```
/trivy --debug config  --format  template --template @contrib/sarif.tpl --exit-code 0 --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL --output  trivy-results.sarif ./terraform/environment
```

For now I'll close this issue as we can track the progress there.

**Comment by williamfalconeruk** [comment]
@simar7 thanks for taking a look - i'll keep an eye on the other issue.
